<h1>Image filters</h1>

<div class="tracy-inner">
	<div class="tracy-inner-container">
		<table class="tracy-sortable">
			<thead>
				<tr style="user-select: none">
					<th>Name</th>
					<th>Filters</th>
				</tr>
			</thead>
			<tbody>
				<?php
					use Contributte\Imagist\Debugger\DebugFilterObject;
					use Contributte\Imagist\Debugger\DebugFilterOperationObject;

					/** @var DebugFilterObject $filter */
					foreach ($this->getFilters() as $filter):
				?>
				<tr>
					<td><strong><?= $filter->getName() ?></strong></td>
					<td><?=
					implode(
						'<br>',
						array_map(
							fn (DebugFilterOperationObject $op) =>
								$op->getName() . ($op->getArguments() ? '(' . implode(', ', $op->getArguments()) . ')' : '') . ($op->getDescription() ? ' - ' . $op->getDescription() : ''),
							$filter->getOperations()
						)
					) ?></td>
				</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>


