<?php /** @var $this Contributte\Imagist\Bridge\Nette\Tracy\ImageBarPanel */ ?>
<h1>Imagist actions</h1>
<table class="tracy-sortable">
	<thead>
		<tr>
			<th>#</th>
			<th>Action</th>
			<th>Source</th>
			<th>Filter</th>
			<th>Result</th>
			<th>Entrypoint</th>
		</tr>
	</thead>
	<tbody>
		<?php foreach ($this->events as $index => $event): ?>
		<tr>
			<td>
				<?= $index + 1 ?>
			</td>
			<td>
				<?= $event->getAction() ?>
			</td>
			<td>
				<?= $event->getSource() ?>
			</td>
			<td>
				<?= $event->getFilter() ?>
			</td>
			<td>
				<?= $event->getResult() ?>
			</td>
			<td>
				<?= $event->getEntrypoint() ?>
			</td>
		</tr>
		<?php endforeach; ?>
	</tbody>
</table>
